name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install modules
        run: npm install

      - name: build production project
        run: npm run build:prod

      if: always()
      - name: linting typescript
        run: npm run lint:ts

      if: always()
      - name: linting scss
        run: npm run lint:scss

      if: always()
      - name: unit testing
        run: npm run test:unit

      - name: build storybook
        run: npm run storybook:build

      if: always()
      - name: screenshot testing
        run: npm run test:ui:ci
      if: always()
